export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST";
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS";
export const ALL_USERS_FAIL = "ALL_USERS_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const DELETE_USER_RESET = "DELETE_USER_RESET";

export const CREATE_BLOG_REQUEST = "CREATE_BLOG_REQUEST";
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";
export const CREATE_BLOG_FAIL = "CREATE_BLOG_FAIL";

export const ALL_BLOG_REQUEST = "ALL_BLOG_REQUEST";
export const ALL_BLOG_SUCCESS = "ALL_BLOG_SUCCESS";
export const ALL_BLOG_FAIL = "ALL_BLOG_FAIL";

export const DELETE_BLOG_REQUEST = "DELETE_BLOG_REQUEST";
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";
export const DELETE_BLOG_FAIL = "DELETE_BLOG_FAIL";
export const DELETE_BLOG_RESET = "DELETE_BLOG_RESET";

export const CREATE_SCHOOL_REQUEST = "CREATE_SCHOOL_REQUEST";
export const CREATE_SCHOOL_SUCCESS = "CREATE_SCHOOL_SUCCESS";
export const CREATE_SCHOOL_FAIL = "CREATE_SCHOOL_FAIL";

export const ALL_SCHOOL_REQUEST = "ALL_SCHOOL_REQUEST";
export const ALL_SCHOOL_SUCCESS = "ALL_SCHOOL_SUCCESS";
export const ALL_SCHOOL_FAIL = "ALL_SCHOOL_FAIL";

export const DELETE_SCHOOL_REQUEST = "DELETE_SCHOOL_REQUEST";
export const DELETE_SCHOOL_SUCCESS = "DELETE_SCHOOL_SUCCESS";
export const DELETE_SCHOOL_FAIL = "DELETE_SCHOOL_FAIL";
export const DELETE_SCHOOL_RESET = "DELETE_SCHOOL_RESET";


export const CREATE_STORY_REQUEST = "CREATE_STORY_REQUEST";
export const CREATE_STORY_SUCCESS = "CREATE_STORY_SUCCESS";
export const CREATE_STORY_FAIL = "CREATE_STORY_FAIL";